[train_params]
data_dir = "/data/solar_wind_pred_vignesh/hdf/"
base_dir = "/data/solar_wind_pred_vignesh"
batch_size = 10
data_transform = ['arcsinh', 'sqrt', 'arcsinh', 'arcsinh', 'arcsinh', 'arcsinh', 'arcsinh', 'arcsinh', 'pow']

[model_params]
model_type = 'ParamNetwork'
scale_up = 1
operator_type = 'local_no'
modes = [109,128]
rank = 0.4
conv_module = 'spherical'
n_layers=4
job_id = '2026_06_03__062346'

[wandb_params]
run_name = 'ParamNetwork_SFNO_v1'
run_id = 'd1i4sx58'
group_name = 'ParamNetwork'
description = 'SFNO Architecture' 